In [127]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

In [128]:
df = pd.read_csv("tmdb_5000_movies.csv")
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [129]:
data = pd.read_csv("tmdb_5000_credits.csv")
data.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [130]:
movie_df = pd.merge(df,data, left_on=['id',"title"], right_on=['movie_id',"title"]).drop(['movie_id'], axis=1)
movie_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [15]:
movie_df.shape

(4803, 22)

In [16]:
movie_df.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                       0
crew                       0
dtype: int64

In [131]:
movie_df = movie_df[["id","title","overview","genres","keywords","cast","crew"]].copy()

In [18]:
movie_df.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        4803 non-null   int64
 1   title     4803 non-null   object
 2   overview  4800 non-null   object
 3   genres    4803 non-null   object
 4   keywords  4803 non-null   object
 5   cast      4803 non-null   object
 6   crew      4803 non-null   object
dtypes: int64(1), object(6)
memory usage: 262.8+ KB

In [20]:
movie_df.isnull().sum()

id          0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [132]:
movie_df.dropna(subset=['overview'], inplace=True)

In [25]:
movie_df.iloc[0]["genres"]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [26]:
ast.literal_eval(movie_df.iloc[0]["genres"])

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [133]:
def convert(obj):
    genres=[]
    for i in ast.literal_eval(obj):
        genres.append(i["name"].lower())
    return genres

In [134]:
movie_df["genres"] = movie_df["genres"].apply(convert)
movie_df["keywords"] = movie_df["keywords"].apply(convert)

In [135]:
movie_df[["genres","keywords"]]

,genres,keywords
0,"[action, adventure, fantasy, science fiction]","[culture clash, future, space war, space colon..."
1,"[adventure, fantasy, action]","[ocean, drug abuse, exotic island, east india ..."
2,"[action, adventure, crime]","[spy, based on novel, secret agent, sequel, mi..."
3,"[action, crime, drama, thriller]","[dc comics, crime fighter, terrorist, secret i..."
4,"[action, adventure, science fiction]","[based on novel, mars, medallion, space travel..."
...,...,...
4798,"[action, crime, thriller]","[united states–mexico barrier, legs, arms, pap..."
4799,"[comedy, romance]",[]
4800,"[comedy, drama, romance, tv movie]","[date, love at first sight, narration, investi..."
4801,[],[]
4802,[documentary],"[obsession, camcorder, crush, dream girl]"

In [31]:
ast.literal_eval(movie_df["cast"][0])

[{'cast_id': 242,
  'character': 'Jake Sully',
  'credit_id': '5602a8a7c3a3685532001c9a',
  'gender': 2,
  'id': 65731,
  'name': 'Sam Worthington',
  'order': 0},
 {'cast_id': 3,
  'character': 'Neytiri',
  'credit_id': '52fe48009251416c750ac9cb',
  'gender': 1,
  'id': 8691,
  'name': 'Zoe Saldana',
  'order': 1},
 {'cast_id': 25,
  'character': 'Dr. Grace Augustine',
  'credit_id': '52fe48009251416c750aca39',
  'gender': 1,
  'id': 10205,
  'name': 'Sigourney Weaver',
  'order': 2},
 {'cast_id': 4,
  'character': 'Col. Quaritch',
  'credit_id': '52fe48009251416c750ac9cf',
  'gender': 2,
  'id': 32747,
  'name': 'Stephen Lang',
  'order': 3},
 {'cast_id': 5,
  'character': 'Trudy Chacon',
  'credit_id': '52fe48009251416c750ac9d3',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 4},
 {'cast_id': 8,
  'character': 'Selfridge',
  'credit_id': '52fe48009251416c750ac9e1',
  'gender': 2,
  'id': 1771,
  'name': 'Giovanni Ribisi',
  'order': 5},
 {'cast_id': 7,
  'character': 'Norm Spellman',
  'credit_id': '52fe48009251416c750ac9dd',
  'gender': 2,
  'id': 59231,
  'name': 'Joel David Moore',
  'order': 6},
 {'cast_id': 9,
  'character': 'Moat',
  'credit_id': '52fe48009251416c750ac9e5',
  'gender': 1,
  'id': 30485,
  'name': 'CCH Pounder',
  'order': 7},
 {'cast_id': 11,
  'character': 'Eytukan',
  'credit_id': '52fe48009251416c750ac9ed',
  'gender': 2,
  'id': 15853,
  'name': 'Wes Studi',
  'order': 8},
 {'cast_id': 10,
  'character': "Tsu'Tey",
  'credit_id': '52fe48009251416c750ac9e9',
  'gender': 2,
  'id': 10964,
  'name': 'Laz Alonso',
  'order': 9},
 {'cast_id': 12,
  'character': 'Dr. Max Patel',
  'credit_id': '52fe48009251416c750ac9f1',
  'gender': 2,
  'id': 95697,
  'name': 'Dileep Rao',
  'order': 10},
 {'cast_id': 13,
  'character': 'Lyle Wainfleet',
  'credit_id': '52fe48009251416c750ac9f5',
  'gender': 2,
  'id': 98215,
  'name': 'Matt Gerald',
  'order': 11},
 {'cast_id': 32,
  'character': 'Private Fike',
  'credit_id': '52fe48009251416c750aca5b',
  'gender': 2,
  'id': 154153,
  'name': 'Sean Anthony Moran',
  'order': 12},
 {'cast_id': 33,
  'character': 'Cryo Vault Med Tech',
  'credit_id': '52fe48009251416c750aca5f',
  'gender': 2,
  'id': 397312,
  'name': 'Jason Whyte',
  'order': 13},
 {'cast_id': 34,
  'character': 'Venture Star Crew Chief',
  'credit_id': '52fe48009251416c750aca63',
  'gender': 2,
  'id': 42317,
  'name': 'Scott Lawrence',
  'order': 14},
 {'cast_id': 35,
  'character': 'Lock Up Trooper',
  'credit_id': '52fe48009251416c750aca67',
  'gender': 2,
  'id': 986734,
  'name': 'Kelly Kilgour',
  'order': 15},
 {'cast_id': 36,
  'character': 'Shuttle Pilot',
  'credit_id': '52fe48009251416c750aca6b',
  'gender': 0,
  'id': 1207227,
  'name': 'James Patrick Pitt',
  'order': 16},
 {'cast_id': 37,
  'character': 'Shuttle Co-Pilot',
  'credit_id': '52fe48009251416c750aca6f',
  'gender': 0,
  'id': 1180936,
  'name': 'Sean Patrick Murphy',
  'order': 17},
 {'cast_id': 38,
  'character': 'Shuttle Crew Chief',
  'credit_id': '52fe48009251416c750aca73',
  'gender': 2,
  'id': 1019578,
  'name': 'Peter Dillon',
  'order': 18},
 {'cast_id': 39,
  'character': 'Tractor Operator / Troupe',
  'credit_id': '52fe48009251416c750aca77',
  'gender': 0,
  'id': 91443,
  'name': 'Kevin Dorman',
  'order': 19},
 {'cast_id': 40,
  'character': 'Dragon Gunship Pilot',
  'credit_id': '52fe48009251416c750aca7b',
  'gender': 2,
  'id': 173391,
  'name': 'Kelson Henderson',
  'order': 20},
 {'cast_id': 41,
  'character': 'Dragon Gunship Gunner',
  'credit_id': '52fe48009251416c750aca7f',
  'gender': 0,
  'id': 1207236,
  'name': 'David Van Horn',
  'order': 21},
 {'cast_id': 42,
  'character': 'Dragon Gunship Navigator',
  'credit_id': '52fe48009251416c750aca83',
  'gender': 0,
  'id': 215913,
  'name': 'Jacob Tomuri',
  'order': 22},
 {'cast_id': 43,
  'character': 'Suit #1',
  'credit_id': '52fe48009251416c750aca87',
  'gender': 0,
  'id': 143206,
  'name': 'Michael Blain-Rozgay',
  'order': 23},
 {'cast_id': 44,
  'character': 'Suit #2',
  'credit_id': '52fe48009251416c750aca8b',
  'gender': 2,
  'id': 169676,
  'name': 'Jon Curry',
  'order': 24},
 {'cast_id': 46,
  'character': 'Ambient Room Tech',
  'credit_id': '52fe48009251416c750aca8f',
  'gender': 0,
  'id': 1048610,
  'name': 'Luke Hawker',
  'order': 25},
 {'cast_id': 47,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48009251416c750aca93',
  'gender': 0,
  'id': 42288,
  'name': 'Woody Schultz',
  'order': 26},
 {'cast_id': 48,
  'character': 'Horse Clan Leader',
  'credit_id': '52fe48009251416c750aca97',
  'gender': 2,
  'id': 68278,
  'name': 'Peter Mensah',
  'order': 27},
 {'cast_id': 49,
  'character': 'Link Room Tech',
  'credit_id': '52fe48009251416c750aca9b',
  'gender': 0,
  'id': 1207247,
  'name': 'Sonia Yee',
  'order': 28},
 {'cast_id': 50,
  'character': 'Basketball Avatar / Troupe',
  'credit_id': '52fe48009251416c750aca9f',
  'gender': 1,
  'id': 1207248,
  'name': 'Jahnel Curfman',
  'order': 29},
 {'cast_id': 51,
  'character': 'Basketball Avatar',
  'credit_id': '52fe48009251416c750acaa3',
  'gender': 0,
  'id': 89714,
  'name': 'Ilram Choi',
  'order': 30},
 {'cast_id': 52,
  'character': "Na'vi Child",
  'credit_id': '52fe48009251416c750acaa7',
  'gender': 0,
  'id': 1207249,
  'name': 'Kyla Warren',
  'order': 31},
 {'cast_id': 53,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaab',
  'gender': 0,
  'id': 1207250,
  'name': 'Lisa Roumain',
  'order': 32},
 {'cast_id': 54,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaaf',
  'gender': 1,
  'id': 83105,
  'name': 'Debra Wilson',
  'order': 33},
 {'cast_id': 57,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabb',
  'gender': 0,
  'id': 1207253,
  'name': 'Chris Mala',
  'order': 34},
 {'cast_id': 55,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab3',
  'gender': 0,
  'id': 1207251,
  'name': 'Taylor Kibby',
  'order': 35},
 {'cast_id': 56,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab7',
  'gender': 0,
  'id': 1207252,
  'name': 'Jodie Landau',
  'order': 36},
 {'cast_id': 58,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabf',
  'gender': 0,
  'id': 1207254,
  'name': 'Julie Lamm',
  'order': 37},
 {'cast_id': 59,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac3',
  'gender': 0,
  'id': 1207257,
  'name': 'Cullen B. Madden',
  'order': 38},
 {'cast_id': 60,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac7',
  'gender': 0,
  'id': 1207259,
  'name': 'Joseph Brady Madden',
  'order': 39},
 {'cast_id': 61,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacb',
  'gender': 0,
  'id': 1207262,
  'name': 'Frankie Torres',
  'order': 40},
 {'cast_id': 62,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacf',
  'gender': 1,
  'id': 1158600,
  'name': 'Austin Wilson',
  'order': 41},
 {'cast_id': 63,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad3',
  'gender': 1,
  'id': 983705,
  'name': 'Sara Wilson',
  'order': 42},
 {'cast_id': 64,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad7',
  'gender': 0,
  'id': 1207263,
  'name': 'Tamica Washington-Miller',
  'order': 43},
 {'cast_id': 65,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadb',
  'gender': 1,
  'id': 1145098,
  'name': 'Lucy Briant',
  'order': 44},
 {'cast_id': 66,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadf',
  'gender': 2,
  'id': 33305,
  'name': 'Nathan Meister',
  'order': 45},
 {'cast_id': 67,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae3',
  'gender': 0,
  'id': 1207264,
  'name': 'Gerry Blair',
  'order': 46},
 {'cast_id': 68,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae7',
  'gender': 2,
  'id': 33311,
  'name': 'Matthew Chamberlain',
  'order': 47},
 {'cast_id': 69,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaeb',
  'gender': 0,
  'id': 1207265,
  'name': 'Paul Yates',
  'order': 48},
 {'cast_id': 70,
  'character': 'Op Center Duty Officer',
  'credit_id': '52fe48019251416c750acaef',
  'gender': 0,
  'id': 1207266,
  'name': 'Wray Wilson',
  'order': 49},
 {'cast_id': 71,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaf3',
  'gender': 2,
  'id': 54492,
  'name': 'James Gaylyn',
  'order': 50},
 {'cast_id': 72,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaf7',
  'gender': 0,
  'id': 1207267,
  'name': 'Melvin Leno Clark III',
  'order': 51},
 {'cast_id': 73,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acafb',
  'gender': 0,
  'id': 1207268,
  'name': 'Carvon Futrell',
  'order': 52},
 {'cast_id': 74,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaff',
  'gender': 0,
  'id': 1207269,
  'name': 'Brandon Jelkes',
  'order': 53},
 {'cast_id': 75,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb03',
  'gender': 0,
  'id': 1207270,
  'name': 'Micah Moch',
  'order': 54},
 {'cast_id': 76,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb07',
  'gender': 0,
  'id': 1207271,
  'name': 'Hanniyah Muhammad',
  'order': 55},
 {'cast_id': 77,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0b',
  'gender': 0,
  'id': 1207272,
  'name': 'Christopher Nolen',
  'order': 56},
 {'cast_id': 78,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0f',
  'gender': 0,
  'id': 1207273,
  'name': 'Christa Oliver',
  'order': 57},
 {'cast_id': 79,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb13',
  'gender': 0,
  'id': 1207274,
  'name': 'April Marie Thomas',
  'order': 58},
 {'cast_id': 80,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb17',
  'gender': 0,
  'id': 1207275,
  'name': 'Bravita A. Threatt',
  'order': 59},
 {'cast_id': 81,
  'character': 'Mining Chief (uncredited)',
  'credit_id': '52fe48019251416c750acb1b',
  'gender': 0,
  'id': 1207276,
  'name': 'Colin Bleasdale',
  'order': 60},
 {'cast_id': 82,
  'character': 'Veteran Miner (uncredited)',
  'credit_id': '52fe48019251416c750acb1f',
  'gender': 0,
  'id': 107969,
  'name': 'Mike Bodnar',
  'order': 61},
 {'cast_id': 83,
  'character': 'Richard (uncredited)',
  'credit_id': '52fe48019251416c750acb23',
  'gender': 0,
  'id': 1207278,
  'name': 'Matt Clayton',
  'order': 62},
 {'cast_id': 84,
  'character': "Nav'i (uncredited)",
  'credit_id': '52fe48019251416c750acb27',
  'gender': 1,
  'id': 147898,
  'name': 'Nicole Dionne',
  'order': 63},
 {'cast_id': 85,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2b',
  'gender': 0,
  'id': 1207280,
  'name': 'Jamie Harrison',
  'order': 64},
 {'cast_id': 86,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2f',
  'gender': 0,
  'id': 1207281,
  'name': 'Allan Henry',
  'order': 65},
 {'cast_id': 87,
  'character': 'Ground Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb33',
  'gender': 2,
  'id': 1207282,
  'name': 'Anthony Ingruber',
  'order': 66},
 {'cast_id': 88,
  'character': 'Flight Crew Mechanic (uncredited)',
  'credit_id': '52fe48019251416c750acb37',
  'gender': 0,
  'id': 1207283,
  'name': 'Ashley Jeffery',
  'order': 67},
 {'cast_id': 14,
  'character': 'Samson Pilot',
  'credit_id': '52fe48009251416c750ac9f9',
  'gender': 0,
  'id': 98216,
  'name': 'Dean Knowsley',
  'order': 68},
 {'cast_id': 89,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb3b',
  'gender': 0,
  'id': 1201399,
  'name': 'Joseph Mika-Hunt',
  'order': 69},
 {'cast_id': 90,
  'character': 'Banshee (uncredited)',
  'credit_id': '52fe48019251416c750acb3f',
  'gender': 0,
  'id': 236696,
  'name': 'Terry Notary',
  'order': 70},
 {'cast_id': 91,
  'character': 'Soldier (uncredited)',
  'credit_id': '52fe48019251416c750acb43',
  'gender': 0,
  'id': 1207287,
  'name': 'Kai Pantano',
  'order': 71},
 {'cast_id': 92,
  'character': 'Blast Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb47',
  'gender': 0,
  'id': 1207288,
  'name': 'Logan Pithyou',
  'order': 72},
 {'cast_id': 93,
  'character': 'Vindum Raah (uncredited)',
  'credit_id': '52fe48019251416c750acb4b',
  'gender': 0,
  'id': 1207289,
  'name': 'Stuart Pollock',
  'order': 73},
 {'cast_id': 94,
  'character': 'Hero (uncredited)',
  'credit_id': '52fe48019251416c750acb4f',
  'gender': 0,
  'id': 584868,
  'name': 'Raja',
  'order': 74},
 {'cast_id': 95,
  'character': 'Ops Centreworker (uncredited)',
  'credit_id': '52fe48019251416c750acb53',
  'gender': 0,
  'id': 1207290,
  'name': 'Gareth Ruck',
  'order': 75},
 {'cast_id': 96,
  'character': 'Engineer (uncredited)',
  'credit_id': '52fe48019251416c750acb57',
  'gender': 0,
  'id': 1062463,
  'name': 'Rhian Sheehan',
  'order': 76},
 {'cast_id': 97,
  'character': "Col. Quaritch's Mech Suit (uncredited)",
  'credit_id': '52fe48019251416c750acb5b',
  'gender': 0,
  'id': 60656,
  'name': 'T. J. Storm',
  'order': 77},
 {'cast_id': 98,
  'character': 'Female Marine (uncredited)',
  'credit_id': '52fe48019251416c750acb5f',
  'gender': 0,
  'id': 1207291,
  'name': 'Jodie Taylor',
  'order': 78},
 {'cast_id': 99,
  'character': 'Ikran Clan Leader (uncredited)',
  'credit_id': '52fe48019251416c750acb63',
  'gender': 1,
  'id': 1186027,
  'name': 'Alicia Vela-Bailey',
  'order': 79},
 {'cast_id': 100,
  'character': 'Geologist (uncredited)',
  'credit_id': '52fe48019251416c750acb67',
  'gender': 0,
  'id': 1207292,
  'name': 'Richard Whiteside',
  'order': 80},
 {'cast_id': 101,
  'character': "Na'vi (uncredited)",
  'credit_id': '52fe48019251416c750acb6b',
  'gender': 0,
  'id': 103259,
  'name': 'Nikie Zambo',
  'order': 81},
 {'cast_id': 102,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48019251416c750acb6f',
  'gender': 1,
  'id': 42286,
  'name': 'Julene Renee',
  'order': 82}]

In [136]:
def cast(obj):
    cast=[]
    count = 0
    for i in ast.literal_eval(obj):
        if count < 5 :
            cast.append(i["name"].lower())
            count = count + 1
        else:
            break
    return cast

In [137]:
movie_df["cast"] = movie_df["cast"].apply(cast)

In [138]:
movie_df["cast"][0]

['sam worthington',
 'zoe saldana',
 'sigourney weaver',
 'stephen lang',
 'michelle rodriguez']

In [71]:
ast.literal_eval(movie_df["crew"][0])

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  'gender': 2,
  'id': 2710,
  'job': 'Director',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750ac9d9',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Writer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca17',
  'department': 'Editing',
  'gender': 2,
  'id': 2710,
  'job': 'Editor',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca29',
  'department': 'Production',
  'gender': 2,
  'id': 2710,
  'job': 'Producer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca3f',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Screenplay',
  'name': 'James Cameron'},
 {'credit_id': '539c4987c3a36810ba0021a4',
  'department': 'Art',
  'gender': 2,
  'id': 7236,
  'job': 'Art Direction',
  'name': 'Andrew Menzies'},
 {'credit_id': '549598c3c3a3686ae9004383',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 6690,
  'job': 'Visual Effects Producer',
  'name': 'Jill Brooks'},
 {'credit_id': '52fe48009251416c750aca4b',
  'department': 'Production',
  'gender': 1,
  'id': 6347,
  'job': 'Casting',
  'name': 'Margery Simkin'},
 {'credit_id': '570b6f419251417da70032fe',
  'department': 'Art',
  'gender': 2,
  'id': 6878,
  'job': 'Supervising Art Director',
  'name': 'Kevin Ishioka'},
 {'credit_id': '5495a0fac3a3686ae9004468',
  'department': 'Sound',
  'gender': 0,
  'id': 6883,
  'job': 'Music Editor',
  'name': 'Dick Bernstein'},
 {'credit_id': '54959706c3a3686af3003e81',
  'department': 'Sound',
  'gender': 0,
  'id': 8159,
  'job': 'Sound Effects Editor',
  'name': 'Shannon Mills'},
 {'credit_id': '54491d58c3a3680fb1001ccb',
  'department': 'Sound',
  'gender': 0,
  'id': 8160,
  'job': 'Foley',
  'name': 'Dennie Thorpe'},
 {'credit_id': '54491d6cc3a3680fa5001b2c',
  'department': 'Sound',
  'gender': 0,
  'id': 8163,
  'job': 'Foley',
  'name': 'Jana Vance'},
 {'credit_id': '52fe48009251416c750aca57',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 8527,
  'job': 'Costume Design',
  'name': 'Deborah Lynn Scott'},
 {'credit_id': '52fe48009251416c750aca2f',
  'department': 'Production',
  'gender': 2,
  'id': 8529,
  'job': 'Producer',
  'name': 'Jon Landau'},
 {'credit_id': '539c4937c3a36810ba002194',
  'department': 'Art',
  'gender': 0,
  'id': 9618,
  'job': 'Art Direction',
  'name': 'Sean Haworth'},
 {'credit_id': '539c49b6c3a36810c10020e6',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Set Decoration',
  'name': 'Kim Sinclair'},
 {'credit_id': '570b6f2f9251413a0e00020d',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Supervising Art Director',
  'name': 'Kim Sinclair'},
 {'credit_id': '54491a6c0e0a26748c001b19',
  'department': 'Art',
  'gender': 2,
  'id': 14350,
  'job': 'Set Designer',
  'name': 'Richard F. Mays'},
 {'credit_id': '56928cf4c3a3684cff0025c4',
  'department': 'Production',
  'gender': 1,
  'id': 20294,
  'job': 'Executive Producer',
  'name': 'Laeta Kalogridis'},
 {'credit_id': '52fe48009251416c750aca51',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 17675,
  'job': 'Costume Design',
  'name': 'Mayes C. Rubeo'},
 {'credit_id': '52fe48009251416c750aca11',
  'department': 'Camera',
  'gender': 2,
  'id': 18265,
  'job': 'Director of Photography',
  'name': 'Mauro Fiore'},
 {'credit_id': '5449194d0e0a26748f001b39',
  'department': 'Art',
  'gender': 0,
  'id': 42281,
  'job': 'Set Designer',
  'name': 'Scott Herbertson'},
 {'credit_id': '52fe48009251416c750aca05',
  'department': 'Crew',
  'gender': 0,
  'id': 42288,
  'job': 'Stunts',
  'name': 'Woody Schultz'},
 {'credit_id': '5592aefb92514152de0010f5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Makeup Artist',
  'name': 'Linda DeVetta'},
 {'credit_id': '5592afa492514152de00112c',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Hairstylist',
  'name': 'Linda DeVetta'},
 {'credit_id': '54959ed592514130fc002e5d',
  'department': 'Camera',
  'gender': 2,
  'id': 33302,
  'job': 'Camera Operator',
  'name': 'Richard Bluck'},
 {'credit_id': '539c4891c3a36810ba002147',
  'department': 'Art',
  'gender': 2,
  'id': 33303,
  'job': 'Art Direction',
  'name': 'Simon Bright'},
 {'credit_id': '54959c069251417a81001f3a',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 113145,
  'job': 'Visual Effects Supervisor',
  'name': 'Richard Martin'},
 {'credit_id': '54959a0dc3a3680ff5002c8d',
  'department': 'Crew',
  'gender': 2,
  'id': 58188,
  'job': 'Visual Effects Editor',
  'name': 'Steve R. Moore'},
 {'credit_id': '52fe48009251416c750aca1d',
  'department': 'Editing',
  'gender': 2,
  'id': 58871,
  'job': 'Editor',
  'name': 'John Refoua'},
 {'credit_id': '54491a4dc3a3680fc30018ca',
  'department': 'Art',
  'gender': 0,
  'id': 92359,
  'job': 'Set Designer',
  'name': 'Karl J. Martin'},
 {'credit_id': '52fe48009251416c750aca35',
  'department': 'Camera',
  'gender': 1,
  'id': 72201,
  'job': 'Director of Photography',
  'name': 'Chiling Lin'},
 {'credit_id': '52fe48009251416c750ac9ff',
  'department': 'Crew',
  'gender': 0,
  'id': 89714,
  'job': 'Stunts',
  'name': 'Ilram Choi'},
 {'credit_id': '54959c529251416e2b004394',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 93214,
  'job': 'Visual Effects Supervisor',
  'name': 'Steven Quale'},
 {'credit_id': '54491edf0e0a267489001c37',
  'department': 'Crew',
  'gender': 1,
  'id': 122607,
  'job': 'Dialect Coach',
  'name': 'Carla Meyer'},
 {'credit_id': '539c485bc3a368653d001a3a',
  'department': 'Art',
  'gender': 2,
  'id': 132585,
  'job': 'Art Direction',
  'name': 'Nick Bassett'},
 {'credit_id': '539c4903c3a368653d001a74',
  'department': 'Art',
  'gender': 0,
  'id': 132596,
  'job': 'Art Direction',
  'name': 'Jill Cormack'},
 {'credit_id': '539c4967c3a368653d001a94',
  'department': 'Art',
  'gender': 0,
  'id': 132604,
  'job': 'Art Direction',
  'name': 'Andy McLaren'},
 {'credit_id': '52fe48009251416c750aca45',
  'department': 'Crew',
  'gender': 0,
  'id': 236696,
  'job': 'Motion Capture Artist',
  'name': 'Terry Notary'},
 {'credit_id': '54959e02c3a3680fc60027d2',
  'department': 'Crew',
  'gender': 2,
  'id': 956198,
  'job': 'Stunt Coordinator',
  'name': 'Garrett Warren'},
 {'credit_id': '54959ca3c3a3686ae300438c',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 957874,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Rothbart'},
 {'credit_id': '570b6f519251412c74001b2f',
  'department': 'Art',
  'gender': 0,
  'id': 957889,
  'job': 'Supervising Art Director',
  'name': 'Stefan Dechant'},
 {'credit_id': '570b6f62c3a3680b77007460',
  'department': 'Art',
  'gender': 2,
  'id': 959555,
  'job': 'Supervising Art Director',
  'name': 'Todd Cherniawsky'},
 {'credit_id': '539c4a3ac3a36810da0021cc',
  'department': 'Production',
  'gender': 0,
  'id': 1016177,
  'job': 'Casting',
  'name': 'Miranda Rivers'},
 {'credit_id': '539c482cc3a36810c1002062',
  'department': 'Art',
  'gender': 0,
  'id': 1032536,
  'job': 'Production Design',
  'name': 'Robert Stromberg'},
 {'credit_id': '539c4b65c3a36810c9002125',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1071680,
  'job': 'Costume Design',
  'name': 'John Harding'},
 {'credit_id': '54959e6692514130fc002e4e',
  'department': 'Camera',
  'gender': 0,
  'id': 1177364,
  'job': 'Steadicam Operator',
  'name': 'Roberto De Angelis'},
 {'credit_id': '539c49f1c3a368653d001aac',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1202850,
  'job': 'Makeup Department Head',
  'name': 'Mike Smithson'},
 {'credit_id': '5495999ec3a3686ae100460c',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1204668,
  'job': 'Visual Effects Producer',
  'name': 'Alain Lalanne'},
 {'credit_id': '54959cdfc3a3681153002729',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1206410,
  'job': 'Visual Effects Supervisor',
  'name': 'Lucas Salton'},
 {'credit_id': '549596239251417a81001eae',
  'department': 'Crew',
  'gender': 0,
  'id': 1234266,
  'job': 'Post Production Supervisor',
  'name': 'Janace Tashjian'},
 {'credit_id': '54959c859251416e1e003efe',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1271932,
  'job': 'Visual Effects Supervisor',
  'name': 'Stephen Rosenbaum'},
 {'credit_id': '5592af28c3a368775a00105f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1310064,
  'job': 'Makeup Artist',
  'name': 'Frankie Karena'},
 {'credit_id': '539c4adfc3a36810e300203b',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1319844,
  'job': 'Costume Supervisor',
  'name': 'Lisa Lovaas'},
 {'credit_id': '54959b579251416e2b004371',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1327028,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Fawkner'},
 {'credit_id': '539c48a7c3a36810b5001fa7',
  'department': 'Art',
  'gender': 0,
  'id': 1330561,
  'job': 'Art Direction',
  'name': 'Robert Bavin'},
 {'credit_id': '539c4a71c3a36810da0021e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330567,
  'job': 'Costume Supervisor',
  'name': 'Anthony Almaraz'},
 {'credit_id': '539c4a8ac3a36810ba0021e4',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330570,
  'job': 'Costume Supervisor',
  'name': 'Carolyn M. Fenton'},
 {'credit_id': '539c4ab6c3a36810da0021f0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330574,
  'job': 'Costume Supervisor',
  'name': 'Beth Koenigsberg'},
 {'credit_id': '54491ab70e0a267480001ba2',
  'department': 'Art',
  'gender': 0,
  'id': 1336191,
  'job': 'Set Designer',
  'name': 'Sam Page'},
 {'credit_id': '544919d9c3a3680fc30018bd',
  'department': 'Art',
  'gender': 0,
  'id': 1339441,
  'job': 'Set Designer',
  'name': 'Tex Kadonaga'},
 {'credit_id': '54491cf50e0a267483001b0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1352422,
  'job': 'Dialogue Editor',
  'name': 'Kim Foscato'},
 {'credit_id': '544919f40e0a26748c001b09',
  'department': 'Art',
  'gender': 0,
  'id': 1352962,
  'job': 'Set Designer',
  'name': 'Tammy S. Lee'},
 {'credit_id': '5495a115c3a3680ff5002d71',
  'department': 'Crew',
  'gender': 0,
  'id': 1357070,
  'job': 'Transportation Coordinator',
  'name': 'Denny Caira'},
 {'credit_id': '5495a12f92514130fc002e94',
  'department': 'Crew',
  'gender': 0,
  'id': 1357071,
  'job': 'Transportation Coordinator',
  'name': 'James Waitkus'},
 {'credit_id': '5495976fc3a36811530026b0',
  'department': 'Sound',
  'gender': 0,
  'id': 1360103,
  'job': 'Supervising Sound Editor',
  'name': 'Addison Teague'},
 {'credit_id': '54491837c3a3680fb1001c5a',
  'department': 'Art',
  'gender': 2,
  'id': 1376887,
  'job': 'Set Designer',
  'name': 'C. Scott Baker'},
 {'credit_id': '54491878c3a3680fb4001c9d',
  'department': 'Art',
  'gender': 0,
  'id': 1376888,
  'job': 'Set Designer',
  'name': 'Luke Caska'},
 {'credit_id': '544918dac3a3680fa5001ae0',
  'department': 'Art',
  'gender': 0,
  'id': 1376889,
  'job': 'Set Designer',
  'name': 'David Chow'},
 {'credit_id': '544919110e0a267486001b68',
  'department': 'Art',
  'gender': 0,
  'id': 1376890,
  'job': 'Set Designer',
  'name': 'Jonathan Dyer'},
 {'credit_id': '54491967c3a3680faa001b5e',
  'department': 'Art',
  'gender': 0,
  'id': 1376891,
  'job': 'Set Designer',
  'name': 'Joseph Hiura'},
 {'credit_id': '54491997c3a3680fb1001c8a',
  'department': 'Art',
  'gender': 0,
  'id': 1376892,
  'job': 'Art Department Coordinator',
  'name': 'Rebecca Jellie'},
 {'credit_id': '544919ba0e0a26748f001b42',
  'department': 'Art',
  'gender': 0,
  'id': 1376893,
  'job': 'Set Designer',
  'name': 'Robert Andrew Johnson'},
 {'credit_id': '54491b1dc3a3680faa001b8c',
  'department': 'Art',
  'gender': 0,
  'id': 1376895,
  'job': 'Assistant Art Director',
  'name': 'Mike Stassi'},
 {'credit_id': '54491b79c3a3680fbb001826',
  'department': 'Art',
  'gender': 0,
  'id': 1376897,
  'job': 'Construction Coordinator',
  'name': 'John Villarino'},
 {'credit_id': '54491baec3a3680fb4001ce6',
  'department': 'Art',
  'gender': 2,
  'id': 1376898,
  'job': 'Assistant Art Director',
  'name': 'Jeffrey Wisniewski'},
 {'credit_id': '54491d2fc3a3680fb4001d07',
  'department': 'Editing',
  'gender': 0,
  'id': 1376899,
  'job': 'Dialogue Editor',
  'name': 'Cheryl Nardi'},
 {'credit_id': '54491d86c3a3680fa5001b2f',
  'department': 'Editing',
  'gender': 0,
  'id': 1376901,
  'job': 'Dialogue Editor',
  'name': 'Marshall Winn'},
 {'credit_id': '54491d9dc3a3680faa001bb0',
  'department': 'Sound',
  'gender': 0,
  'id': 1376902,
  'job': 'Supervising Sound Editor',
  'name': 'Gwendolyn Yates Whittle'},
 {'credit_id': '54491dc10e0a267486001bce',
  'department': 'Sound',
  'gender': 0,
  'id': 1376903,
  'job': 'Sound Re-Recording Mixer',
  'name': 'William Stein'},
 {'credit_id': '54491f500e0a26747c001c07',
  'department': 'Crew',
  'gender': 0,
  'id': 1376909,
  'job': 'Choreographer',
  'name': 'Lula Washington'},
 {'credit_id': '549599239251412c4e002a2e',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1391692,
  'job': 'Visual Effects Producer',
  'name': 'Chris Del Conte'},
 {'credit_id': '54959d54c3a36831b8001d9a',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1391695,
  'job': 'Visual Effects Supervisor',
  'name': 'R. Christopher White'},
 {'credit_id': '54959bdf9251412c4e002a66',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394070,
  'job': 'Visual Effects Supervisor',
  'name': 'Dan Lemmon'},
 {'credit_id': '5495971d92514132ed002922',
  'department': 'Sound',
  'gender': 0,
  'id': 1394129,
  'job': 'Sound Effects Editor',
  'name': 'Tim Nielsen'},
 {'credit_id': '5592b25792514152cc0011aa',
  'department': 'Crew',
  'gender': 0,
  'id': 1394286,
  'job': 'CG Supervisor',
  'name': 'Michael Mulholland'},
 {'credit_id': '54959a329251416e2b004355',
  'department': 'Crew',
  'gender': 0,
  'id': 1394750,
  'job': 'Visual Effects Editor',
  'name': 'Thomas Nittmann'},
 {'credit_id': '54959d6dc3a3686ae9004401',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394755,
  'job': 'Visual Effects Supervisor',
  'name': 'Edson Williams'},
 {'credit_id': '5495a08fc3a3686ae300441c',
  'department': 'Editing',
  'gender': 0,
  'id': 1394953,
  'job': 'Digital Intermediate',
  'name': 'Christine Carr'},
 {'credit_id': '55402d659251413d6d000249',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1395269,
  'job': 'Visual Effects Supervisor',
  'name': 'John Bruno'},
 {'credit_id': '54959e7b9251416e1e003f3e',
  'department': 'Camera',
  'gender': 0,
  'id': 1398970,
  'job': 'Steadicam Operator',
  'name': 'David Emmerichs'},
 {'credit_id': '54959734c3a3686ae10045e0',
  'department': 'Sound',
  'gender': 0,
  'id': 1400906,
  'job': 'Sound Effects Editor',
  'name': 'Christopher Scarabosio'},
 {'credit_id': '549595dd92514130fc002d79',
  'department': 'Production',
  'gender': 0,
  'id': 1401784,
  'job': 'Production Supervisor',
  'name': 'Jennifer Teves'},
 {'credit_id': '549596009251413af70028cc',
  'department': 'Production',
  'gender': 0,
  'id': 1401785,
  'job': 'Production Manager',
  'name': 'Brigitte Yorke'},
 {'credit_id': '549596e892514130fc002d99',
  'department': 'Sound',
  'gender': 0,
  'id': 1401786,
  'job': 'Sound Effects Editor',
  'name': 'Ken Fischer'},
 {'credit_id': '549598229251412c4e002a1c',
  'department': 'Crew',
  'gender': 0,
  'id': 1401787,
  'job': 'Special Effects Coordinator',
  'name': 'Iain Hutton'},
 {'credit_id': '549598349251416e2b00432b',
  'department': 'Crew',
  'gender': 0,
  'id': 1401788,
  'job': 'Special Effects Coordinator',
  'name': 'Steve Ingram'},
 {'credit_id': '54959905c3a3686ae3004324',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401789,
  'job': 'Visual Effects Producer',
  'name': 'Joyce Cox'},
 {'credit_id': '5495994b92514132ed002951',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401790,
  'job': 'Visual Effects Producer',
  'name': 'Jenny Foster'},
 {'credit_id': '549599cbc3a3686ae1004613',
  'department': 'Crew',
  'gender': 0,
  'id': 1401791,
  'job': 'Visual Effects Editor',
  'name': 'Christopher Marino'},
 {'credit_id': '549599f2c3a3686ae100461e',
  'department': 'Crew',
  'gender': 0,
  'id': 1401792,
  'job': 'Visual Effects Editor',
  'name': 'Jim Milton'},
 {'credit_id': '54959a51c3a3686af3003eb5',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401793,
  'job': 'Visual Effects Producer',
  'name': 'Cyndi Ochs'},
 {'credit_id': '54959a7cc3a36811530026f4',
  'department': 'Crew',
  'gender': 0,
  'id': 1401794,
  'job': 'Visual Effects Editor',
  'name': 'Lucas Putnam'},
 {'credit_id': '54959b91c3a3680ff5002cb4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401795,
  'job': 'Visual Effects Supervisor',
  'name': "Anthony 'Max' Ivins"},
 {'credit_id': '54959bb69251412c4e002a5f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401796,
  'job': 'Visual Effects Supervisor',
  'name': 'John Knoll'},
 {'credit_id': '54959cbbc3a3686ae3004391',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1401799,
  'job': 'Visual Effects Supervisor',
  'name': 'Eric Saindon'},
 {'credit_id': '54959d06c3a3686ae90043f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401800,
  'job': 'Visual Effects Supervisor',
  'name': 'Wayne Stables'},
 {'credit_id': '54959d259251416e1e003f11',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401801,
  'job': 'Visual Effects Supervisor',
  'name': 'David Stinnett'},
 {'credit_id': '54959db49251413af7002975',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401803,
  'job': 'Visual Effects Supervisor',
  'name': 'Guy Williams'},
 {'credit_id': '54959de4c3a3681153002750',
  'department': 'Crew',
  'gender': 0,
  'id': 1401804,
  'job': 'Stunt Coordinator',
  'name': 'Stuart Thorp'},
 {'credit_id': '54959ef2c3a3680fc60027f2',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401805,
  'job': 'Best Boy Electric',
  'name': 'Giles Coburn'},
 {'credit_id': '54959f07c3a3680fc60027f9',
  'department': 'Camera',
  'gender': 2,
  'id': 1401806,
  'job': 'Still Photographer',
  'name': 'Mark Fellman'},
 {'credit_id': '54959f47c3a3681153002774',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401807,
  'job': 'Lighting Technician',
  'name': 'Scott Sprague'},
 {'credit_id': '54959f8cc3a36831b8001df2',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401808,
  'job': 'Animation Director',
  'name': 'Jeremy Hollobon'},
 {'credit_id': '54959fa0c3a36831b8001dfb',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401809,
  'job': 'Animation Director',
  'name': 'Orlando Meunier'},
 {'credit_id': '54959fb6c3a3686af3003f54',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401810,
  'job': 'Animation Director',
  'name': 'Taisuke Tanimura'},
 {'credit_id': '54959fd2c3a36831b8001e02',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1401812,
  'job': 'Set Costumer',
  'name': 'Lilia Mishel Acevedo'},

In [139]:
def director(obj):
    director = []
    for i in ast.literal_eval(obj):
        if i["job"]=='Director':
            director.append(i["name"].lower())
    return director

In [140]:
movie_df["director"] = movie_df["crew"].apply(director)

In [74]:
movie_df["director"][0]

['james cameron']

In [141]:
movie_df.drop(["crew"],axis=1,inplace=True)

In [142]:
movie_df.head()

,id,title,overview,genres,keywords,cast,director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[action, adventure, fantasy, science fiction]","[culture clash, future, space war, space colon...","[sam worthington, zoe saldana, sigourney weave...",[james cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[adventure, fantasy, action]","[ocean, drug abuse, exotic island, east india ...","[johnny depp, orlando bloom, keira knightley, ...",[gore verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[action, adventure, crime]","[spy, based on novel, secret agent, sequel, mi...","[daniel craig, christoph waltz, léa seydoux, r...",[sam mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[action, crime, drama, thriller]","[dc comics, crime fighter, terrorist, secret i...","[christian bale, michael caine, gary oldman, a...",[christopher nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[action, adventure, science fiction]","[based on novel, mars, medallion, space travel...","[taylor kitsch, lynn collins, samantha morton,...",[andrew stanton]

In [ ]:
movie_df["genres_x"] = movie_df["genres"].apply(lambda x: [i.replace(" ","") for i in x])
movie_df["keywords"] = movie_df["keywords"].apply(lambda x: [i.replace(" ","") for i in x])
movie_df["cast"] = movie_df["cast"].apply(lambda x: [i.replace(" ","") for i in x])
movie_df["director_x"] = movie_df["director"].apply(lambda x: [i.replace(" ","") for i in x])

In [ ]:
movie_df['tags'] = movie_df["genres_x"] + movie_df["keywords"] + movie_df["cast"] + movie_df["director_x"]

In [ ]:
movie_df.drop(columns=["genres_x","keywords","cast","director_x"], inplace=True)

In [146]:
movie_df.head(3)

,id,title,overview,genres,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[action, adventure, fantasy, science fiction]","[action, adventure, fantasy, sciencefiction, c..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[adventure, fantasy, action]","[adventure, fantasy, action, ocean, drugabuse,..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[action, adventure, crime]","[action, adventure, crime, spy, basedonnovel, ..."

In [147]:
movie_df["tags"] = movie_df["tags"].apply(lambda x: " ".join(x))

In [148]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfv = TfidfVectorizer(stop_words='english')
vectors = tfv.fit_transform(movie_df['tags']).toarray()

In [149]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [156]:
similarity.shape

(4800, 4800)

In [159]:
list(enumerate(similarity[0]))

[(0, np.float64(1.0)),
 (1, np.float64(0.02022189992925108)),
 (2, np.float64(0.01472083476783116)),
 (3, np.float64(0.004300318586006985)),
 (4, np.float64(0.0927598205403137)),
 (5, np.float64(0.020809846858107488)),
 (6, np.float64(0.0)),
 (7, np.float64(0.053091016348571926)),
 (8, np.float64(0.019279370233520596)),
 (9, np.float64(0.024953376959127666)),
 (10, np.float64(0.034299512534417084)),
 (11, np.float64(0.016404111206556965)),
 (12, np.float64(0.0223393084186604)),
 (13, np.float64(0.011665038629804936)),
 (14, np.float64(0.03634413538124549)),
 (15, np.float64(0.016792039304778187)),
 (16, np.float64(0.025539003382812696)),
 (17, np.float64(0.0987025854144366)),
 (18, np.float64(0.045732276930566924)),
 (19, np.float64(0.05209529998846597)),
 (20, np.float64(0.022142367785814913)),
 (21, np.float64(0.013356998435862195)),
 (22, np.float64(0.019690232214635825)),
 (23, np.float64(0.018924170511687054)),
 (24, np.float64(0.013059027049971694)),
 (25, np.float64(0.061423022499690325)),
 (26, np.float64(0.049277544945508914)),
 (27, np.float64(0.014098210863523366)),
 (28, np.float64(0.038851672894907076)),
 (29, np.float64(0.012012716058420369)),
 (30, np.float64(0.024131371208456247)),
 (31, np.float64(0.038291694870971955)),
 (32, np.float64(0.06142667419196466)),
 (33, np.float64(0.026464852661990557)),
 (34, np.float64(0.0)),
 (35, np.float64(0.022671132744930805)),
 (36, np.float64(0.05287085488069722)),
 (37, np.float64(0.04285059977067348)),
 (38, np.float64(0.025611708520139997)),
 (39, np.float64(0.022172780615336597)),
 (40, np.float64(0.008878464848994806)),
 (41, np.float64(0.07195796775590942)),
 (42, np.float64(0.0)),
 (43, np.float64(0.06203564355947495)),
 (44, np.float64(0.061174924839262186)),
 (45, np.float64(0.016778453508838238)),
 (46, np.float64(0.03585536789607428)),
 (47, np.float64(0.21133868065572656)),
 (48, np.float64(0.022091485554781583)),
 (49, np.float64(0.03793296707987272)),
 (50, np.float64(0.03296179833916976)),
 (51, np.float64(0.05193513597667005)),
 (52, np.float64(0.06999547013562633)),
 (53, np.float64(0.01084258093772222)),
 (54, np.float64(0.0068136599580863825)),
 (55, np.float64(0.035337024924576084)),
 (56, np.float64(0.08309801045907672)),
 (57, np.float64(0.0)),
 (58, np.float64(0.007979553444906884)),
 (59, np.float64(0.020560025908019898)),
 (60, np.float64(0.0)),
 (61, np.float64(0.10787405571955541)),
 (62, np.float64(0.014854329848345317)),
 (63, np.float64(0.04635971977656847)),
 (64, np.float64(0.009960466085702833)),
 (65, np.float64(0.004572809248879269)),
 (66, np.float64(0.0075791640351536)),
 (67, np.float64(0.055316834397887975)),
 (68, np.float64(0.021575112904042425)),
 (69, np.float64(0.0261676970286066)),
 (70, np.float64(0.02772189739616073)),
 (71, np.float64(0.03751293847312646)),
 (72, np.float64(0.035220454183257865)),
 (73, np.float64(0.009913056356169977)),
 (74, np.float64(0.07249793253072942)),
 (75, np.float64(0.015218808114722617)),
 (76, np.float64(0.02056664368312002)),
 (77, np.float64(0.02128031358781602)),
 (78, np.float64(0.01688378354076087)),
 (79, np.float64(0.028522114682935466)),
 (80, np.float64(0.01625896581209483)),
 (81, np.float64(0.05115860364824024)),
 (82, np.float64(0.03439521536163861)),
 (83, np.float64(0.040508322388689524)),
 (84, np.float64(0.04465712065654177)),
 (85, np.float64(0.07314514429567566)),
 (86, np.float64(0.058230696273587464)),
 (87, np.float64(0.01730474740418232)),
 (88, np.float64(0.02970558086934795)),
 (89, np.float64(0.005319265682648758)),
 (90, np.float64(0.016190043585702172)),
 (91, np.float64(0.030548458936655823)),
 (92, np.float64(0.04153721209985206)),
 (93, np.float64(0.0132374731178635)),
 (94, np.float64(0.11146098770013416)),
 (95, np.float64(0.06121124505586169)),
 (96, np.float64(0.023227588532261707)),
 (97, np.float64(0.021348575118552204)),
 (98, np.float64(0.016957223521965027)),
 (99, np.float64(0.05709687750938285)),
 (100, np.float64(0.020875502155860023)),
 (101, np.float64(0.022361790803943026)),
 (102, np.float64(0.05497295243022304)),
 (103, np.float64(0.02025892529407322)),
 (104, np.float64(0.010790407390063926)),
 (105, np.float64(0.0369422622403308)),
 (106, np.float64(0.012727959746810813)),
 (107, np.float64(0.020512271563874723)),
 (108, np.float64(0.07813431211780343)),
 (109, np.float64(0.01793604054452821)),
 (110, np.float64(0.006619701963899189)),
 (111, np.float64(0.05177936121668834)),
 (112, np.float64(0.01883877587641505)),
 (113, np.float64(0.01608956296174665)),
 (114, np.float64(0.01643180163803034)),
 (115, np.float64(0.016057302405643747)),
 (116, np.float64(0.014450386263469811)),
 (117, np.float64(0.018558183816253508)),
 (118, np.float64(0.007914676808277435)),
 (119, np.float64(0.042826109472680104)),
 (120, np.float64(0.0)),
 (121, np.float64(0.029074604760870128)),
 (122, np.float64(0.027305817887726472)),
 (123, np.float64(0.032329616796256844)),
 (124, np.float64(0.025578537019465334)),
 (125, np.float64(0.03746562418802865)),
 (126, np.float64(0.04877702482159699)),
 (127, np.float64(0.048754281432602804)),
 (128, np.float64(0.0)),
 (129, np.float64(0.04096530403203737)),
 (130, np.float64(0.006935242890112996)),
 (131, np.float64(0.03278603045154009)),
 (132, np.float64(0.07436487975316108)),
 (133, np.float64(0.009262236751268737)),
 (134, np.float64(0.013838486262222224)),
 (135, np.float64(0.0)),
 (136, np.float64(0.006563639255827143)),
 (137, np.float64(0.0)),
 (138, np.float64(0.01926520319798438)),
 (139, np.float64(0.00800667482409417)),
 (140, np.float64(0.007240014750258804)),
 (141, np.float64(0.033668980114992066)),
 (142, np.float64(0.007889072275520872)),
 (143, np.float64(0.020138922388814286)),
 (144, np.float64(0.005374852254436738)),
 (145, np.float64(0.005270126100903572)),
 (146, np.float64(0.028270570030258936)),
 (147, np.float64(0.015388347671136905)),
 (148, np.float64(0.01970637070817011)),
 (149, np.float64(0.052353622656004184)),
 (150, np.float64(0.04484687373340103)),
 (151, np.float64(0.038677785454849026)),
 (152, np.float64(0.012168224392438793)),
 (153, np.float64(0.014928711635085821)),
 (154, np.float64(0.011448047741197096)),
 (155, np.float64(0.0)),
 (156, np.float64(0.040912152649785746)),
 (157, np.float64(0.042736642001734375)),
 (158, np.float64(0.0567252396526525)),
 (159, np.float64(0.016246822722893732)),
 (160, np.float64(0.04715244617517594)),
 (161, np.float64(0.00943685473493117)),
 (162, np.float64(0.007989536534111729)),
 (163, np.float64(0.01274702854031439)),
 (164, np.float64(0.016398096438851033)),
 (165, np.float64(0.010478028663588443)),
 (166, np.float64(0.0517480494013076)),
 (167, np.float64(0.016445020457297364)),
 (168, np.float64(0.06140196503676072)),
 (169, np.float64(0.04366986929675856)),
 (170, np.float64(0.014326928091058497)),
 (171, np.float64(0.007563651268241194)),
 (172, np.float64(0.024126279303166527)),
 (173, np.float64(0.02738798309809506)),
 (174, np.float64(0.01953040654846515)),
 (175, np.float64(0.01899937241601351)),
 (176, np.float64(0.005961823160672953)),
 (177, np.float64(0.0)),
 (178, np.float64(0.006454994797345785)),
 (179, np.float64(0.033764765944009144)),
 (180, np.float64(0.00408202015118945)),
 (181, np.float64(0.005284179304163559)),
 (182, np.float64(0.054995406212068804)),
 (183, np.float64(0.0400717259893783)),
 (184, np.float64(0.08215988420651914)),
 (185, np.float64(0.01937853934544198)),
 (186, np.float64(0.009041498042843779)),
 (187, np.float64(0.04078226368832654)),
 (188, np.float64(0.004540947984528885)),
 (189, np.float64(0.03955114381846585)),
 (190, np.float64(0.036007166458932184)),
 (191, np.float64(0.015465873280326729)),
 (192, np.float64(0.0)),
 (193, np.float64(0.03294559362890073)),
 (194, np.float64(0.0)),
 (195, np.float64(0.021799696753737826)),
 (196, np.float64(0.013115362965917426)),
 (197, np.float64(0.018211607228233385)),
 (198, np.float64(0.018002371332899905)),
 (199, np.float64(0.018245303883674128)),
 (200, np.float64(0.016011825487803756)),
 (201, np.float64(0.0)),
 (202, np.float64(0.008378563792987574)),
 (203, np.float64(0.029639456227234552)),
 (204, np.float64(0.004984209583513175)),
 (205, np.float64(0.015989659831034092)),
 (206, np.float64(0.08215101793238205)),
 (207, np.float64(0.06509464499747233)),
 (208, np.float64(0.023160673111286452)),
 (209, np.float64(0.004036690581657373)),
 (210, np.float64(0.017108630352894408)),
 (211, np.float64(0.0127301558579634)),
 (212, np.float64(0.014301946051913813)),
 (213, np.float64(0.010724298862521443)),
 (214, np.float64(0.0)),
 (215, np.float64(0.01669429242050649)),
 (216, np.float64(0.011750154140945074)),
 (217, np.float64(0.016764869574437628)),
 (218, np.float64(0.00804073879782642)),
 (219, np.float64(0.018562456304940626)),
 (220, np.float64(0.03526174461971667)),
 (221, np.float64(0.00831702683477834)),
 (222, np.float64(0.019691792361656607)),
 (223, np.float64(0.018614384554520944)),
 (224, np.float64(0.05474546309232564)),
 (225, np.float64(0.018019057436011968)),
 (226, np.float64(0.00856506838212112)),
 (227, np.float64(0.005327284425760806)),
 (228, np.float64(0.06309980419568262)),
 (229, np.float64(0.020420013428207262)),
 (230, np.float64(0.01792069188073366)),
 (231, np.float64(0.0)),
 (232, np.float64(0.035838633018509654)),
 (233, np.float64(0.023506536138546016)),
 (234, np.float64(0.018921813806645017)),
 (235, np.float64(0.0157629932060064)),
 (236, np.float64(0.005788377692751153)),
 (237, np.float64(0.014730394285889625)),
 (238, np.float64(0.049893629180298396)),
 (239, np.float64(0.053713763550001396)),
 (240, np.float64(0.009100103258075467)),
 (241, np.float64(0.02690267487150845)),
 (242, np.float64(0.020684675348414165)),
 (243, np.float64(0.02036677479782014)),
 (244, np.float64(0.028466815927508684)),
 (245, np.float64(0.010724913883482248)),
 (246, np.float64(0.004966445895800446)),
 (247, np.float64(0.0)),
 (248, np.float64(0.0051610040450625295)),
 (249, np.float64(0.04477962221827574)),
 (250, np.float64(0.0)),
 (251, np.float64(0.027192442814717194)),
 (252, np.float64(0.004979999745585882)),
 (253, np.float64(0.02850193755319439)),
 (254, np.float64(0.01709107688349266)),
 (255, np.float64(0.0)),
 (256, np.float64(0.020529466397679712)),
 (257, np.float64(0.016450047476001695)),
 (258, np.float64(0.013544568188434572)),
 (259, np.float64(0.014173822391403879)),
 (260, np.float64(0.11466843417115044)),
 (261, np.float64(0.00418417720202579)),
 (262, np.float64(0.019725223454519616)),
 (263, np.float64(0.013718613186486442)),
 (264, np.float64(0.0)),
 (265, np.float64(0.01205238175625048)),
 (266, np.float64(0.06825462311098143)),
 (267, np.float64(0.012177986293233287)),
 (268, np.float64(0.010665760206113064)),
 (269, np.float64(0.0054494988607794595)),
 (270, np.float64(0.048355661074227854)),
 (271, np.float64(0.02425417715681135)),
 (272, np.float64(0.008050321883734083)),
 (273, np.float64(0.004310389346318104)),
 (274, np.float64(0.010005984159972937)),
 (275, np.float64(0.045488750998641414)),
 (276, np.float64(0.017372218196276067)),
 (277, np.float64(0.012894333277164723)),
 (278, np.float64(0.10972736716430948)),
 (279, np.float64(0.05765360977009566)),
 (280, np.float64(0.0)),
 (281, np.float64(0.045410305982683766)),
 (282, np.float64(0.046861445965024506)),
 (283, np.float64(0.0)),
 (284, np.float64(0.007843269037147752)),
 (285, np.float64(0.005709724823816063)),
 (286, np.float64(0.004039965521063076)),
 (287, np.float64(0.04275961403651972)),
 (288, np.float64(0.0)),
 (289, np.float64(0.01860478509039758)),
 (290, np.float64(0.012998177797454352)),
 (291, np.float64(0.015891475843009113)),
 (292, np.float64(0.02724031727511577)),
 (293, np.float64(0.009233272189172193)),
 (294, np.float64(0.03896658661104552)),
 (295, np.float64(0.023961938674434472)),
 (296, np.float64(0.01146424623666652)),
 (297, np.float64(0.004761013374139041)),
 (298, np.float64(0.0)),
 (299, np.float64(0.012405065527202105)),
 (300, np.float64(0.04923196221910915)),
 (301, np.float64(0.042587441869116005)),
 (302, np.float64(0.022596662974370935)),
 (303, np.float64(0.004956969047001932)),
 (304, np.float64(0.05269708949821193)),
 (305, np.float64(0.06974910311937392)),
 (306, np.float64(0.019878838842752516)),
 (307, np.float64(0.05258761802445715)),
 (308, np.float64(0.03355228774021914)),
 (309, np.float64(0.022311112369558336)),
 (310, np.float64(0.00946128821290418)),
 (311, np.float64(0.05137867750688912)),
 (312, np.float64(0.01588748443795691)),
 (313, np.float64(0.024300811403435724)),
 (314, np.float64(0.0)),
 (315, np.float64(0.02963988514391723)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.02086443291677776)),
 (320, np.float64(0.005678941108777658)),
 (321, np.float64(0.0)),
 (322, np.float64(0.0897717997882421)),
 (323, np.float64(0.009880348387090988)),
 (324, np.float64(0.008877948506449036)),
 (325, np.float64(0.0061710975586442545)),
 (326, np.float64(0.017378508325268632)),
 (327, np.float64(0.010396135060842492)),
 (328, np.float64(0.0)),
 (329, np.float64(0.020593473916160156)),
 (330, np.float64(0.020107570698180234)),
 (331, np.float64(0.019949517051348425)),
 (332, np.float64(0.02270412493888127)),
 (333, np.float64(0.007869448453756934)),
 (334, np.float64(0.02104676057276586)),
 (335, np.float64(0.01474151048418207)),
 (336, np.float64(0.017006942794121238)),
 (337, np.float64(0.006122614622937788)),
 (338, np.float64(0.0)),
 (339, np.float64(0.013132144665915672)),
 (340, np.float64(0.014366077636116562)),
 (341, np.float64(0.019886086905394156)),
 (342, np.float64(0.042216472030561406)),
 (343, np.float64(0.0)),
 (344, np.float64(0.008127587137939067)),
 (345, np.float64(0.0079757675925768)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.03340336252641232)),
 (349, np.float64(0.015607892184886944)),
 (350, np.float64(0.017039770804984235)),
 (351, np.float64(0.0)),
 (352, np.float64(0.0070591616581679026)),
 (353, np.float64(0.00511974988412458)),
 (354, np.float64(0.0)),
 (355, np.float64(0.004274875947756964)),
 (356, np.float64(0.01244659563922387)),
 (357, np.float64(0.0)),
 (358, np.float64(0.0173168372880565)),
 (359, np.float64(0.07549949143570053)),
 (360, np.float64(0.0)),
 (361, np.float64(0.0048055797511974)),
 (362, np.float64(0.04422540725919609)),
 (363, np.float64(0.03430475688760459)),
 (364, np.float64(0.011938172085234292)),
 (365, np.float64(0.007359571715094994)),
 (366, np.float64(0.017894423754716483)),
 (367, np.float64(0.0)),
 (368, np.float64(0.0363607548307459)),
 (369, np.float64(0.020907834002441554)),
 (370, np.float64(0.012751533402458746)),
 (371, np.float64(0.03233949780677784)),
 (372, np.float64(0.007201782259658496)),
 (373, np.float64(0.07076588149742616)),
 (374, np.float64(0.007356717974629434)),
 (375, np.float64(0.07117716650413998)),
 (376, np.float64(0.017336018348613324)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.026579768104664087)),
 (380, np.float64(0.005836179444372882)),
 (381, np.float64(0.024054811016669786)),
 (382, np.float64(0.0)),
 (383, np.float64(0.010871551195743383)),
 (384, np.float64(0.007495712695872155)),
 (385, np.float64(0.0)),
 (386, np.float64(0.004568021903988435)),
 (387, np.float64(0.0042580334406269165)),
 (388, np.float64(0.0)),
 (389, np.float64(0.039946575098991716)),
 (390, np.float64(0.00967780594097279)),
 (391, np.float64(0.017723637264908776)),
 (392, np.float64(0.006303053274630921)),
 (393, np.float64(0.0)),
 (394, np.float64(0.004286945575913289)),
 (395, np.float64(0.0068296624213210234)),
 (396, np.float64(0.004302875190238681)),
 (397, np.float64(0.009449722647432787)),
 (398, np.float64(0.0)),
 (399, np.float64(0.006659474691290818)),
 (400, np.float64(0.025372985603870753)),
 (401, np.float64(0.0)),
 (402, np.float64(0.014169943310790998)),
 (403, np.float64(0.021953924348126055)),
 (404, np.float64(0.007405400600215836)),
 (405, np.float64(0.004857519275756079)),
 (406, np.float64(0.0)),
 (407, np.float64(0.01139269088899807)),
 (408, np.float64(0.006048163170496562)),
 (409, np.float64(0.0)),
 (410, np.float64(0.019822393493099985)),
 (411, np.float64(0.01177245877373136)),
 (412, np.float64(0.027819230200261023)),
 (413, np.float64(0.03059721173347482)),
 (414, np.float64(0.008543777360598814)),
 (415, np.float64(0.043751973938143215)),
 (416, np.float64(0.014934803039555116)),
 (417, np.float64(0.009938279016862115)),
 (418, np.float64(0.031265302121445585)),
 (419, np.float64(0.027783875644643453)),
 (420, np.float64(0.022090532517109865)),
 (421, np.float64(0.0)),
 (422, np.float64(0.04019253590400328)),
 (423, np.float64(0.0105076677242822)),
 (424, np.float64(0.012488123572606334)),
 (425, np.float64(0.010611175827096983)),
 (426, np.float64(0.022411419582056443)),
 (427, np.float64(0.0)),
 (428, np.float64(0.013317775802468006)),
 (429, np.float64(0.0)),
 (430, np.float64(0.0)),
 (431, np.float64(0.009187860781314993)),
 (432, np.float64(0.012035655853527519)),
 (433, np.float64(0.006185592224961926)),
 (434, np.float64(0.0)),
 (435, np.float64(0.012675712095087523)),
 (436, np.float64(0.0)),
 (437, np.float64(0.00631392243992294)),
 (438, np.float64(0.009675427462820223)),
 (439, np.float64(0.0)),
 (440, np.float64(0.009269179700022567)),
 (441, np.float64(0.01128441221431021)),
 (442, np.float64(0.011494137610554879)),
 (443, np.float64(0.01708847929536664)),
 (444, np.float64(0.0)),
 (445, np.float64(0.007587536934633743)),
 (446, np.float64(0.0045591563361961265)),
 (447, np.float64(0.005997095514138189)),
 (448, np.float64(0.0)),
 (449, np.float64(0.01746979199387145)),
 (450, np.float64(0.009907943250630553)),
 (451, np.float64(0.007694167337736188)),
 (452, np.float64(0.008412453099720635)),
 (453, np.float64(0.006049295278055441)),
 (454, np.float64(0.02528604689935399)),
 (455, np.float64(0.00434089410783414)),
 (456, np.float64(0.006463800901339553)),
 (457, np.float64(0.025158908403620537)),
 (458, np.float64(0.03346795431083678)),
 (459, np.float64(0.0063322472147784945)),
 (460, np.float64(0.007134896025168712)),
 (461, np.float64(0.02198664125541614)),
 (462, np.float64(0.0)),
 (463, np.float64(0.0073437445052415345)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.06926141085955018)),
 (467, np.float64(0.03309228249036136)),
 (468, np.float64(0.005682318882260266)),
 (469, np.float64(0.013702758949255309)),
 (470, np.float64(0.017918200570535406)),
 (471, np.float64(0.022211037071088513)),
 (472, np.float64(0.02927975701515402)),
 (473, np.float64(0.020171281937036746)),
 (474, np.float64(0.0)),
 (475, np.float64(0.013347195741974675)),
 (476, np.float64(0.02262183637926176)),
 (477, np.float64(0.0)),
 (478, np.float64(0.01020811768672209)),
 (479, np.float64(0.038008262307446306)),
 (480, np.float64(0.014304728304259138)),
 (481, np.float64(0.0)),
 (482, np.float64(0.005445463883820235)),
 (483, np.float64(0.022297758779704323)),
 (484, np.float64(0.008593012428371972)),
 (485, np.float64(0.016694674170790173)),
 (486, np.float64(0.028405823950205036)),
 (487, np.float64(0.051504996392477714)),
 (488, np.float64(0.01971949636466733)),
 (489, np.float64(0.0)),
 (490, np.float64(0.03748650655305166)),
 (491, np.float64(0.032258622771407904)),
 (492, np.float64(0.02892927157220605)),
 (493, np.float64(0.005936461447234069)),
 (494, np.float64(0.0)),
 (495, np.float64(0.05612655250611758)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.008350718286837672)),
 (499, np.float64(0.0)),
 (500, np.float64(0.006502232997101104)),
 (501, np.float64(0.0402246309411528)),
 (502, np.float64(0.0313732332441198)),
 (503, np.float64(0.021998558291319786)),
 (504, np.float64(0.0)),
 (505, np.float64(0.024681105513702468)),
 (506, np.float64(0.023224435061587022)),
 (507, np.float64(0.079884259359079)),
 (508, np.float64(0.023195557286540294)),
 (509, np.float64(0.0)),
 (510, np.float64(0.04200816934460214)),
 (511, np.float64(0.029806502174003567)),

In [160]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda vec: vec[1])

[(0, np.float64(1.0)),
 (47, np.float64(0.21133868065572656)),
 (2403, np.float64(0.19822992703950926)),
 (838, np.float64(0.12738064036742375)),
 (1201, np.float64(0.12378344203299946)),
 (1580, np.float64(0.11499695088841383)),
 (260, np.float64(0.11466843417115044)),
 (94, np.float64(0.11146098770013416)),
 (278, np.float64(0.10972736716430948)),
 (1287, np.float64(0.10880224625213934)),
 (61, np.float64(0.10787405571955541)),
 (1473, np.float64(0.10077542507815153)),
 (17, np.float64(0.0987025854144366)),
 (4399, np.float64(0.0977018046498811)),
 (2896, np.float64(0.09673802396511932)),
 (3157, np.float64(0.09671891204124583)),
 (582, np.float64(0.0947800095066292)),
 (754, np.float64(0.09413199138463682)),
 (539, np.float64(0.09357011579757404)),
 (4, np.float64(0.0927598205403137)),
 (322, np.float64(0.0897717997882421)),
 (855, np.float64(0.08924226207926889)),
 (3729, np.float64(0.08874369796009875)),
 (1922, np.float64(0.08681162400797579)),
 (1939, np.float64(0.08597084955177257)),
 (3404, np.float64(0.08383975356698908)),
 (1099, np.float64(0.083681316866932)),
 (56, np.float64(0.08309801045907672)),
 (3183, np.float64(0.0822778705081749)),
 (184, np.float64(0.08215988420651914)),
 (206, np.float64(0.08215101793238205)),
 (541, np.float64(0.08019504287237682)),
 (507, np.float64(0.079884259359079)),
 (3533, np.float64(0.0798182733624176)),
 (2389, np.float64(0.07974021700956803)),
 (4330, np.float64(0.07954723212833212)),
 (578, np.float64(0.07919403948741496)),
 (1825, np.float64(0.07867915167289502)),
 (108, np.float64(0.07813431211780343)),
 (671, np.float64(0.07735271158134618)),
 (3623, np.float64(0.07719825688568135)),
 (778, np.float64(0.07654187647974915)),
 (359, np.float64(0.07549949143570053)),
 (132, np.float64(0.07436487975316108)),
 (2327, np.float64(0.07385721009136902)),
 (942, np.float64(0.07373262392756061)),
 (1448, np.float64(0.07352278422088329)),
 (3723, np.float64(0.07329270361946788)),
 (85, np.float64(0.07314514429567566)),
 (2695, np.float64(0.07266785902186551)),
 (1491, np.float64(0.07250256492731244)),
 (74, np.float64(0.07249793253072942)),
 (1395, np.float64(0.07207249294397816)),
 (41, np.float64(0.07195796775590942)),
 (3371, np.float64(0.0717663451376908)),
 (661, np.float64(0.07149116463224184)),
 (375, np.float64(0.07117716650413998)),
 (2198, np.float64(0.07116171321039627)),
 (3444, np.float64(0.07087464102100793)),
 (1080, np.float64(0.07085422893014308)),
 (373, np.float64(0.07076588149742616)),
 (52, np.float64(0.06999547013562633)),
 (4780, np.float64(0.06988023657612517)),
 (305, np.float64(0.06974910311937392)),
 (466, np.float64(0.06926141085955018)),
 (1873, np.float64(0.06863584561352859)),
 (266, np.float64(0.06825462311098143)),
 (1433, np.float64(0.06814942076679517)),
 (4700, np.float64(0.06605638869007636)),
 (1390, np.float64(0.06603782877307551)),
 (1309, np.float64(0.06557998928965039)),
 (579, np.float64(0.0655435359948631)),
 (4263, np.float64(0.06547097751578645)),
 (1191, np.float64(0.06535260644081897)),
 (207, np.float64(0.06509464499747233)),
 (1892, np.float64(0.0642276912684023)),
 (2229, np.float64(0.0641169215434834)),
 (3438, np.float64(0.06381449597347576)),
 (3312, np.float64(0.06358359565027402)),
 (1938, np.float64(0.06351985694277942)),
 (643, np.float64(0.06347669466208153)),
 (2633, np.float64(0.06329699007612452)),
 (1984, np.float64(0.06317002643847353)),
 (228, np.float64(0.06309980419568262)),
 (587, np.float64(0.06293820151425476)),
 (3213, np.float64(0.06279345246035871)),
 (574, np.float64(0.0624215934222941)),
 (43, np.float64(0.06203564355947495)),
 (4585, np.float64(0.06193435728760183)),
 (1012, np.float64(0.0618052175782681)),
 (32, np.float64(0.06142667419196466)),
 (25, np.float64(0.061423022499690325)),
 (168, np.float64(0.06140196503676072)),
 (2500, np.float64(0.061314791676102834)),
 (95, np.float64(0.06121124505586169)),
 (44, np.float64(0.061174924839262186)),
 (1086, np.float64(0.06043924104530489)),
 (1053, np.float64(0.05999340003703481)),
 (1602, np.float64(0.05989810249495202)),
 (3857, np.float64(0.05953498554145926)),
 (1199, np.float64(0.05912329335095733)),
 (931, np.float64(0.059017297662702174)),
 (2153, np.float64(0.05897080768957714)),
 (2492, np.float64(0.05846071145974447)),
 (1146, np.float64(0.058332517788102826)),
 (2372, np.float64(0.05829729350129059)),
 (3043, np.float64(0.05829596595170267)),
 (86, np.float64(0.058230696273587464)),
 (1990, np.float64(0.05788916772224138)),
 (279, np.float64(0.05765360977009566)),
 (1245, np.float64(0.057208072740560896)),
 (99, np.float64(0.05709687750938285)),
 (2244, np.float64(0.05692838459615367)),
 (740, np.float64(0.05688141894706247)),
 (158, np.float64(0.0567252396526525)),
 (657, np.float64(0.05653820598646811)),
 (495, np.float64(0.05612655250611758)),
 (1611, np.float64(0.055952487584873624)),
 (1680, np.float64(0.05580397501128177)),
 (1068, np.float64(0.05567651348452256)),
 (1372, np.float64(0.05546309421686499)),
 (67, np.float64(0.055316834397887975)),
 (182, np.float64(0.054995406212068804)),
 (102, np.float64(0.05497295243022304)),
 (224, np.float64(0.05474546309232564)),
 (1272, np.float64(0.054694889761939376)),
 (2802, np.float64(0.054305363173970604)),
 (3142, np.float64(0.05404235752791346)),
 (2147, np.float64(0.05375682780597856)),
 (239, np.float64(0.053713763550001396)),
 (557, np.float64(0.05333898011771747)),
 (7, np.float64(0.053091016348571926)),
 (36, np.float64(0.05287085488069722)),
 (3322, np.float64(0.05286979559051743)),
 (304, np.float64(0.05269708949821193)),
 (307, np.float64(0.05258761802445715)),
 (2127, np.float64(0.052465045275627856)),
 (3104, np.float64(0.05238046308243415)),
 (149, np.float64(0.052353622656004184)),
 (1525, np.float64(0.05233113432326724)),
 (4223, np.float64(0.052189819484817476)),
 (19, np.float64(0.05209529998846597)),
 (1891, np.float64(0.05193654150785496)),
 (51, np.float64(0.05193513597667005)),
 (1506, np.float64(0.05180851259367325)),
 (111, np.float64(0.05177936121668834)),
 (1574, np.float64(0.05177739708158448)),
 (166, np.float64(0.0517480494013076)),
 (1028, np.float64(0.05164221979880713)),
 (487, np.float64(0.051504996392477714)),
 (4245, np.float64(0.0514692239783001)),
 (1319, np.float64(0.05144846065150241)),
 (2361, np.float64(0.05138395965745879)),
 (311, np.float64(0.05137867750688912)),
 (1153, np.float64(0.05122453629291619)),
 (81, np.float64(0.05115860364824024)),
 (692, np.float64(0.05083181020451193)),
 (1044, np.float64(0.05072268763759287)),
 (1531, np.float64(0.05028447620874807)),
 (2545, np.float64(0.05028303199005014)),
 (238, np.float64(0.049893629180298396)),
 (1291, np.float64(0.049294868300281125)),
 (26, np.float64(0.049277544945508914)),
 (300, np.float64(0.04923196221910915)),
 (4634, np.float64(0.04922959680598796)),
 (939, np.float64(0.049227605625323564)),
 (2391, np.float64(0.04917362558849279)),
 (2867, np.float64(0.04907010919762052)),
 (126, np.float64(0.04877702482159699)),
 (127, np.float64(0.048754281432602804)),
 (2754, np.float64(0.04849588287461406)),
 (270, np.float64(0.048355661074227854)),
 (889, np.float64(0.0481741789078508)),
 (2444, np.float64(0.04816363216213011)),
 (589, np.float64(0.04786902791446001)),
 (2106, np.float64(0.047724894276464064)),
 (4113, np.float64(0.04732203223234923)),
 (1481, np.float64(0.047277369355640655)),
 (1914, np.float64(0.04722776741762114)),
 (1083, np.float64(0.047161680673500156)),
 (160, np.float64(0.04715244617517594)),
 (617, np.float64(0.04710607857861436)),
 (4160, np.float64(0.046993333712812994)),
 (4090, np.float64(0.04696100126563055)),
 (2103, np.float64(0.046948134016619264)),
 (577, np.float64(0.04691603674924134)),
 (282, np.float64(0.046861445965024506)),
 (737, np.float64(0.046812294137744556)),
 (3473, np.float64(0.04678927181739651)),
 (3519, np.float64(0.0467303122568463)),
 (1079, np.float64(0.04660898635470101)),
 (63, np.float64(0.04635971977656847)),
 (4648, np.float64(0.04635273802656008)),
 (2777, np.float64(0.04631155030537401)),
 (1804, np.float64(0.04577537195063344)),
 (18, np.float64(0.045732276930566924)),
 (1326, np.float64(0.04549982768850668)),
 (275, np.float64(0.045488750998641414)),
 (1127, np.float64(0.04542242634750255)),
 (281, np.float64(0.045410305982683766)),
 (1399, np.float64(0.04537900301925314)),
 (791, np.float64(0.04535021675064231)),
 (1354, np.float64(0.045340520023229365)),
 (3230, np.float64(0.04534040608481918)),
 (4185, np.float64(0.0452812398720358)),
 (2965, np.float64(0.04512849532697451)),
 (150, np.float64(0.04484687373340103)),
 (249, np.float64(0.04477962221827574)),
 (647, np.float64(0.04471498398726006)),
 (84, np.float64(0.04465712065654177)),
 (2757, np.float64(0.044562797355604575)),
 (1213, np.float64(0.04441192038262016)),
 (362, np.float64(0.04422540725919609)),
 (1198, np.float64(0.04422000258433438)),
 (415, np.float64(0.043751973938143215)),
 (169, np.float64(0.04366986929675856)),
 (799, np.float64(0.043453757417823494)),
 (752, np.float64(0.043445326173936615)),
 (999, np.float64(0.043387424495624015)),
 (1877, np.float64(0.043383006254135936)),
 (1932, np.float64(0.04325670293824009)),
 (1766, np.float64(0.04322673342239095)),
 (1019, np.float64(0.04322211675173461)),
 (624, np.float64(0.043121946242584974)),
 (1422, np.float64(0.04309254081871892)),
 (790, np.float64(0.04300904001274904)),
 (803, np.float64(0.04285248442494987)),
 (37, np.float64(0.04285059977067348)),
 (4072, np.float64(0.042849853142485794)),
 (119, np.float64(0.042826109472680104)),
 (3201, np.float64(0.042812191065276936)),
 (287, np.float64(0.04275961403651972)),
 (157, np.float64(0.042736642001734375)),
 (301, np.float64(0.042587441869116005)),
 (3055, np.float64(0.042519513636667124)),
 (2138, np.float64(0.04224168453454896)),
 (342, np.float64(0.042216472030561406)),
 (3737, np.float64(0.042036285817024455)),
 (510, np.float64(0.04200816934460214)),
 (775, np.float64(0.04179106952666849)),
 (2654, np.float64(0.04176003102349941)),
 (92, np.float64(0.04153721209985206)),
 (3617, np.float64(0.04140708161109596)),
 (2826, np.float64(0.04121723815989304)),
 (4462, np.float64(0.04112669410805525)),
 (129, np.float64(0.04096530403203737)),
 (156, np.float64(0.040912152649785746)),
 (187, np.float64(0.04078226368832654)),
 (83, np.float64(0.040508322388689524)),
 (2482, np.float64(0.04032204714669523)),
 (501, np.float64(0.0402246309411528)),
 (422, np.float64(0.04019253590400328)),
 (1822, np.float64(0.040135744548095716)),
 (2712, np.float64(0.04010283936491973)),
 (183, np.float64(0.0400717259893783)),
 (1569, np.float64(0.040048992435725225)),
 (389, np.float64(0.039946575098991716)),
 (2163, np.float64(0.03992344558969392)),
 (1426, np.float64(0.03979861051033792)),
 (3064, np.float64(0.0396953413574479)),
 (4618, np.float64(0.039654206748605876)),
 (2069, np.float64(0.03955404660369255)),
 (189, np.float64(0.03955114381846585)),
 (3903, np.float64(0.039501190615425195)),
 (1759, np.float64(0.039436890962176514)),
 (1662, np.float64(0.03936280615456938)),
 (1568, np.float64(0.039343890157409765)),
 (2350, np.float64(0.03932394029064451)),
 (2577, np.float64(0.03920328229565302)),
 (294, np.float64(0.03896658661104552)),
 (3207, np.float64(0.038900176277565326)),
 (2241, np.float64(0.038859812004902065)),
 (28, np.float64(0.038851672894907076)),
 (1652, np.float64(0.0388493345406842)),
 (3435, np.float64(0.03877310297759618)),
 (151, np.float64(0.038677785454849026)),
 (2725, np.float64(0.0385047807152447)),
 (4635, np.float64(0.03846528933263065)),
 (3339, np.float64(0.03835468081187984)),
 (31, np.float64(0.038291694870971955)),
 (2653, np.float64(0.038286855320965596)),
 (2278, np.float64(0.03812463937686549)),
 (2887, np.float64(0.03803034592419597)),
 (479, np.float64(0.038008262307446306)),
 (49, np.float64(0.03793296707987272)),
 (1439, np.float64(0.03791853605857802)),
 (71, np.float64(0.03751293847312646)),
 (2060, np.float64(0.03749257340920441)),
 (490, np.float64(0.03748650655305166)),
 (125, np.float64(0.03746562418802865)),
 (2834, np.float64(0.03743807986216929)),
 (807, np.float64(0.03739715970677993)),
 (1923, np.float64(0.03737827575337958)),
 (1951, np.float64(0.037040878407628215)),
 (900, np.float64(0.03698998160064442)),
 (105, np.float64(0.0369422622403308)),
 (3733, np.float64(0.03691967688639526)),
 (908, np.float64(0.036729557163777835)),
 (536, np.float64(0.03663939800076129)),
 (1192, np.float64(0.03654355059556561)),
 (562, np.float64(0.03637300116536954)),
 (368, np.float64(0.0363607548307459)),
 (14, np.float64(0.03634413538124549)),
 (704, np.float64(0.03630686253399159)),
 (190, np.float64(0.036007166458932184)),
 (3853, np.float64(0.035871077998742514)),
 (46, np.float64(0.03585536789607428)),
 (232, np.float64(0.035838633018509654)),
 (787, np.float64(0.03581978844274804)),
 (814, np.float64(0.03579512778978459)),
 (549, np.float64(0.03577884625258247)),
 (1178, np.float64(0.03577435593005069)),
 (3923, np.float64(0.0356940803757902)),
 (4249, np.float64(0.03563562201138405)),
 (55, np.float64(0.035337024924576084)),
 (220, np.float64(0.03526174461971667)),
 (72, np.float64(0.035220454183257865)),
 (1094, np.float64(0.03518163048697445)),
 (812, np.float64(0.03482771172301924)),
 (4107, np.float64(0.03482063718379143)),
 (4038, np.float64(0.03463813628886177)),
 (1277, np.float64(0.03462579758556094)),
 (3537, np.float64(0.0345048182933627)),
 (2450, np.float64(0.034498501766986864)),
 (2015, np.float64(0.03443491576358415)),
 (82, np.float64(0.03439521536163861)),
 (363, np.float64(0.03430475688760459)),
 (10, np.float64(0.034299512534417084)),
 (4532, np.float64(0.034213657204641354)),
 (1377, np.float64(0.03417203817291875)),
 (1762, np.float64(0.034160154658795634)),
 (1230, np.float64(0.03399790467935846)),
 (3489, np.float64(0.03397291032580401)),
 (4504, np.float64(0.03384091544167775)),
 (770, np.float64(0.03383328494810989)),
 (1601, np.float64(0.033771747460724845)),
 (179, np.float64(0.033764765944009144)),
 (141, np.float64(0.033668980114992066)),
 (1106, np.float64(0.03363881481663496)),
 (308, np.float64(0.03355228774021914)),
 (458, np.float64(0.03346795431083678)),
 (348, np.float64(0.03340336252641232)),
 (2780, np.float64(0.033316248735809906)),
 (3551, np.float64(0.03330401985073613)),
 (546, np.float64(0.03319416486965121)),
 (467, np.float64(0.03309228249036136)),
 (50, np.float64(0.03296179833916976)),
 (193, np.float64(0.03294559362890073)),
 (2985, np.float64(0.03280398169286516)),
 (131, np.float64(0.03278603045154009)),
 (937, np.float64(0.03260087361101088)),
 (2541, np.float64(0.03249540838202562)),
 (2509, np.float64(0.0324153221183096)),
 (371, np.float64(0.03233949780677784)),
 (123, np.float64(0.032329616796256844)),
 (1826, np.float64(0.03229239914950306)),
 (1694, np.float64(0.03228495349150494)),
 (572, np.float64(0.03225933459864182)),
 (491, np.float64(0.032258622771407904)),
 (1204, np.float64(0.03194602485667027)),
 (972, np.float64(0.031779575252731875)),
 (4158, np.float64(0.03174092225069698)),
 (1318, np.float64(0.031691829732978995)),
 (2380, np.float64(0.031394311835867314)),
 (502, np.float64(0.0313732332441198)),
 (3023, np.float64(0.03129191523448332)),
 (418, np.float64(0.031265302121445585)),
 (715, np.float64(0.03123582257243051)),
 (4242, np.float64(0.031180743980901458)),
 (3855, np.float64(0.031167038714075813)),
 (870, np.float64(0.031144980974505083)),
 (3493, np.float64(0.031038113590204516)),
 (859, np.float64(0.03086339502169822)),
 (666, np.float64(0.030777510120061934)),
 (2093, np.float64(0.030758220478508205)),
 (4476, np.float64(0.030752765744873026)),
 (2317, np.float64(0.030749355380543263)),
 (1244, np.float64(0.030700300268802473)),
 (599, np.float64(0.030695379134384342)),
 (1999, np.float64(0.030658308365579465)),
 (413, np.float64(0.03059721173347482)),
 (1296, np.float64(0.03056526066623163)),
 (1495, np.float64(0.03055094443051634)),
 (91, np.float64(0.030548458936655823)),
 (2235, np.float64(0.030522696380710805)),
 (1535, np.float64(0.03046134461566744)),
 (2680, np.float64(0.030261803743549604)),
 (935, np.float64(0.030061483958811985)),
 (1918, np.float64(0.0300537298441583)),
 (786, np.float64(0.029986880431800686)),
 (977, np.float64(0.029986559761323556)),
 (1015, np.float64(0.029973451248994677)),
 (898, np.float64(0.0298995152944474)),
 (629, np.float64(0.029892109250099445)),
 (1016, np.float64(0.029821611523477825)),
 (511, np.float64(0.029806502174003567)),
 (1259, np.float64(0.02972880664362764)),
 (88, np.float64(0.02970558086934795)),
 (2443, np.float64(0.02965879691261524)),
 (315, np.float64(0.02963988514391723)),
 (203, np.float64(0.029639456227234552)),
 (621, np.float64(0.02961647475923341)),
 (3603, np.float64(0.02958485552720516)),
 (781, np.float64(0.029574696820385105)),
 (2227, np.float64(0.02955673323858214)),
 (1802, np.float64(0.029516075932470978)),
 (1936, np.float64(0.02947084105056757)),
 (777, np.float64(0.029406794551338312)),
 (472, np.float64(0.02927975701515402)),
 (1715, np.float64(0.029277697078064033)),
 (4116, np.float64(0.029136295827898586)),
 (121, np.float64(0.029074604760870128)),
 (492, np.float64(0.02892927157220605)),
 (612, np.float64(0.028910814923014724)),
 (837, np.float64(0.028840960743898254)),
 (3592, np.float64(0.028682117749045777)),
 (732, np.float64(0.028675299905238955)),
 (4539, np.float64(0.028610280924833933)),
 (1420, np.float64(0.028544915018754155)),
 (543, np.float64(0.028534400516188652)),
 (2592, np.float64(0.02852298743334165)),
 (79, np.float64(0.028522114682935466)),
 (253, np.float64(0.02850193755319439)),
 (813, np.float64(0.028467635364953267)),
 (244, np.float64(0.028466815927508684)),
 (486, np.float64(0.028405823950205036)),
 (146, np.float64(0.028270570030258936)),
 (1001, np.float64(0.02813887204508294)),
 (1640, np.float64(0.028035996304040106)),
 (564, np.float64(0.027939660540669885)),
 (1768, np.float64(0.027858677890644265)),
 (1155, np.float64(0.027842621012501026)),
 (412, np.float64(0.027819230200261023)),
 (1110, np.float64(0.02779074608914746)),
 (419, np.float64(0.027783875644643453)),
 (70, np.float64(0.02772189739616073)),
 (1902, np.float64(0.027684235059346016)),
 (635, np.float64(0.027630715126626508)),
 (654, np.float64(0.027476469097167618)),
 (173, np.float64(0.02738798309809506)),
 (3645, np.float64(0.027383137149163458)),
 (3465, np.float64(0.02737013755095135)),
 (3992, np.float64(0.02733157816084203)),
 (122, np.float64(0.027305817887726472)),
 (1667, np.float64(0.027299618788054238)),
 (2614, np.float64(0.027277004591758414)),
 (292, np.float64(0.02724031727511577)),
 (251, np.float64(0.027192442814717194)),
 (1947, np.float64(0.02715502550814368)),
 (1324, np.float64(0.02704924473673695)),
 (241, np.float64(0.02690267487150845)),
 (945, np.float64(0.026795018449796336)),
 (1905, np.float64(0.026653098418251708)),
 (2850, np.float64(0.02658818638773586)),
 (379, np.float64(0.026579768104664087)),
 (776, np.float64(0.02657807482056851)),
 (4437, np.float64(0.026556327697164074)),
 (3774, np.float64(0.02655556369961979)),
 (33, np.float64(0.026464852661990557)),
 (2638, np.float64(0.026252158935499547)),
 (1626, np.float64(0.026246799994463527)),
 (976, np.float64(0.026246296501059904)),
 (2087, np.float64(0.02619222573476098)),
 (3809, np.float64(0.026181687954439634)),
 (69, np.float64(0.0261676970286066)),
 (547, np.float64(0.026159557844119514)),
 (768, np.float64(0.0261500878515525)),
 (1518, np.float64(0.02607015793937198)),
 (607, np.float64(0.026022148589199493)),
 (1322, np.float64(0.025979821204211447)),
 (660, np.float64(0.025943758464170304)),
 (3470, np.float64(0.025912719709620457)),
 (2825, np.float64(0.02586539839355949)),
 (1669, np.float64(0.025857479040930123)),
 (701, np.float64(0.02581047535270934)),
 (2655, np.float64(0.025765501003945753)),
 (1437, np.float64(0.025715611756185943)),
 (2129, np.float64(0.025634065782526562)),
 (38, np.float64(0.025611708520139997)),
 (124, np.float64(0.025578537019465334)),

In [170]:
def recommend(movie_title,num_recommendations):
    # Check if the movie exists in the DataFrame
    if movie_title not in movie_df['title'].values:
        print(f"Movie '{movie_title}' not found in the database.")
        return

    # Find the index of the movie in the DataFrame
    index = movie_df[movie_df['title'] == movie_title].index[0]

    # Get the genre of the specified movie
    movie_genre = movie_df.iloc[index]['genres']

    # Calculate the similarity distances
    distance = list(enumerate(similarity[index]))
    movie_list = sorted(distance, reverse=True, key=lambda vec: vec[1])

    # Print the title and genre of the specified movie
    print(f"Recommendations for '{movie_title}' , Genre is: {movie_genre} \n") # 

    # Print the titles and genres of the top 5 similar movies
    count = 1
    for i in movie_list[1:num_recommendations+1]:  # skipping the first result as it's the same movie
        title = movie_df.iloc[i[0]]['title']
        genre = movie_df.iloc[i[0]]['genres']
        overview = movie_df.iloc[i[0]]['overview']
        print(f" Movie {count}: {title} , Genre: {genre},\n Overview: {overview}\n")
        count += 1

In [161]:
movie_df.iloc[47]

id                                                      54138
title                                 Star Trek Into Darkness
overview    When the crew of the Enterprise is called back...
genres                   [action, adventure, science fiction]
tags        action adventure sciencefiction spacecraft fri...
Name: 47, dtype: object

In [171]:
# Use recommend function with "movie title" and "number of recommendations"

movie_name = input("Enter movie name: ")
num = int(input("Enter number of recommendations: "))

recommend(movie_name,num)

Recommendations for 'Avatar' , Genre is: ['action', 'adventure', 'fantasy', 'science fiction']

 Movie 1: Star Trek Into Darkness , Genre: ['action', 'adventure', 'science fiction'],
 Overview: When the crew of the Enterprise is called back home, they find an unstoppable force of terror from within their own organization has detonated the fleet and everything it stands for, leaving our world in a state of crisis.  With a personal score to settle, Captain Kirk leads a manhunt to a war-zone world to capture a one man weapon of mass destruction. As our heroes are propelled into an epic chess game of life and death, love will be challenged, friendships will be torn apart, and sacrifices must be made for the only family Kirk has left: his crew.

 Movie 2: Aliens , Genre: ['horror', 'action', 'thriller', 'science fiction'],
 Overview: When Ripley's lifepod is found by a salvage crew over 50 years later, she finds that terra-formers are on the very planet they found the alien species. When the company sends a family of colonists out to investigate her story, all contact is lost with the planet and colonists. They enlist Ripley and the colonial marines to return and search for answers.

 Movie 3: Alien³ , Genre: ['science fiction', 'action', 'horror'],
 Overview: After escaping with Newt and Hicks from the alien planet, Ripley crash lands on Fiorina 161, a prison planet and host to a correctional facility. Unfortunately, although Newt and Hicks do not survive the crash, a more unwelcome visitor does. The prison does not allow weapons of any kind, and with aid being a long time away, the prisoners must simply survive in any way they can.

 Movie 4: Predators , Genre: ['action', 'science fiction', 'adventure', 'thriller'],
 Overview: A mercenary reluctantly leads a motley crew of warriors who soon come to realize they've been captured and deposited on an alien planet by an unknown nemesis. With the exception of a peculiar physician, they are all cold-blooded killers, convicts, death squad members... hunters who have now become the hunted.

 Movie 5: The Nut Job , Genre: ['animation', 'comedy', 'family', 'adventure'],
 Overview: Surly, a curmudgeon, independent squirrel is banished from his park and forced to survive in the city. Lucky for him, he stumbles on the one thing that may be able to save his life, and the rest of park community, as they gear up for winter - Maury's Nut Store.

In [172]:
import pickle

with open('similarity.pkl', 'wb') as file:
    pickle.dump(similarity, file)

with open('movie_df.plk','wb') as file:
    pickle.dump(movie_df,file)